version: '3'

services:
  service:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - '.:/usr/src/app'
    depends_on:
      - 'database'
    command: /bin/sh -c "yarn && yarn develop"

  database:
    image: 'mongo:4.2'
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'
