version: '3'

services:
  service:
    image: "node:9.5.0-alpine"
    ports: 
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
    working_dir: "/usr/src/app"
    command: /bin/sh -c "yarn && yarn dev"